### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by surdaft** [SplitmediaLabsLimited/devctl#9]
**Description**
On initial global install of devctl, using `nvm` and `node 8.11.3` I receive a type error about `Cannot read property 'map' of undefined`. I have not initialised any configs or anything, this is just to see what commands were available.

Note: This also happens on version 12 and is likely because I have no custom commands present yet, which is unexpected.

**Expected**
To be able to execute `devctl` with no errors and see a list of available commands.

**Output**
```
➜  redacted_project_name ✗ npm install -g @splitmedialabs/devctl
/home/jackstupple/.nvm/versions/node/v8.11.3/bin/devctl -> /home/jackstupple/.nvm/versions/node/v8.11.3/lib/node_modules/@splitmedialabs/devctl/bin/devctl

> ejs@2.7.4 postinstall /home/jackstupple/.nvm/versions/node/v8.11.3/lib/node_modules/@splitmedialabs/devctl/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

+ @splitmedialabs/devctl@3.1.0
added 191 packages in 12.065s
➜ redacted_project_name ✗ devctl
error devctl configuration not found
devctl version 3.1.0

  exec          Execute a command in a running container                                               
  init          Initialize projects and services for devctl                                            
  run           Run a one-off command on a service                                                     
  down          Stops containers and removes containers, networks, volumes, and images created by "up" 
  switch        Switch services and/or environment                                                     
  up            Builds, creates, starts, and attaches to containers for a service                      
  help (h)      -                                                                                      
  logs          View output from containers                                                            
  version (v)   Output the version number                                                              
  status        Output information about the current settings                                          

Custom commands: 

/home/jackstupple/.nvm/versions/node/v8.11.3/lib/node_modules/@splitmedialabs/devctl/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: Cannot read property 'map' of undefined
    at getCustomCommands (/home/jackstupple/.nvm/versions/node/v8.11.3/lib/node_modules/@splitmedialabs/devctl/src/commands/devctl.js:12:27)
    at Command.run (/home/jackstupple/.nvm/versions/node/v8.11.3/lib/node_modules/@splitmedialabs/devctl/src/commands/devctl.js:31:7)
    at Runtime.<anonymous> (/home/jackstupple/.nvm/versions/node/v8.11.3/lib/node_modules/@splitmedialabs/devctl/node_modules/gluegun/build/runtime/run.js:118:58)
    at step (/home/jackstupple/.nvm/versions/node/v8.11.3/lib/node_modules/@splitmedialabs/devctl/node_modules/gluegun/build/runtime/run.js:44:23)
    at Object.next (/home/jackstupple/.nvm/versions/node/v8.11.3/lib/node_modules/@splitmedialabs/devctl/node_modules/gluegun/build/runtime/run.js:25:53)
    at fulfilled (/home/jackstupple/.nvm/versions/node/v8.11.3/lib/node_modules/@splitmedialabs/devctl/node_modules/gluegun/build/runtime/run.js:16:58)
    at <anonymous>
➜  redacted_project_name ✗ node -v
v8.11.3
➜  redacted_project_name ✗ 
```

**Comment by maktouch** [comment]
Hi, 

Just curious - how have you stumbled upon this? I open sourced this from XSplit's repo because I wanted to use it in my other projects/companies. 

I'll do a quick fix. 

Cheers

**Comment by surdaft** [comment]
Hey @maktouch,

I'm a buddy of Oyed's. :)

Cheers, Jack

**Comment by nicodoggie** [comment]
closing as stale

**Comment by nicodoggie** [comment]
Closing as stale
